export const REPO_NAME = "REPO_NAME"
export const REPO_OWNER = "REPO_OWNER"

export const REPO_NAME_REQUEST = 'REPO_NAME_REQUEST'
export const REPO_NAME_SUCCESS = 'REPO_NAME_SUCCESS'
export const REPO_NAME_FAILURE = 'REPO_NAME_FAILURE'

export const REPO_OWNER_REQUEST = 'REPO_OWNER_REQUEST'
export const REPO_OWNER_SUCCESS = 'REPO_OWNER_SUCCESS'
export const REPO_OWNER_FAILURE = 'REPO_OWNER_FAILURE'

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
export const RESET_SEARCH = 'RESET_SEARCH'
