export const REPO_URL = "REPO_URL"

export const REPO_NAME_REQUEST = 'REPO_NAME_REQUEST'
export const REPO_NAME_SUCCESS = 'REPO_NAME_SUCCESS'
export const REPO_NAME_FAILURE = 'REPO_NAME_FAILURE'

export const REPO_OWNER_REQUEST = 'REPO_OWNER_REQUEST'
export const REPO_OWNER_SUCCESS = 'REPO_OWNER_SUCCESS'
export const REPO_OWNER_FAILURE = 'REPO_OWNER_FAILURE'

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
export const RESET_SEARCH = 'RESET_SEARCH'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const TOGGLE_SLIDE_DRAWER =  'TOGGLE_SLIDE_DRAWER'
export const NAVBAR_TITLE =  'NAVBAR_TITLE'

export const GITHUB_ICON_POPOVER_TOGGLE = 'GITHUB_ICON_POPOVER_TOGGLE'
export const GITHUB_ICON_POPOVER_ANCHOR = 'GITHUB_ICON_POPOVER_ANCHOR'
export const SET_GITHUB_ICON_POPOVER_ANCHOR = 'SET_GITHUB_ICON_POPOVER_ANCHOR'

export const CONTACT_SNACK_BAR_TOGGLE = 'CONTACT_SNACK_BAR_TOGGLE'

export const OWNER_INFO_REQUEST = 'OWNER_INFO_REQUEST'
export const OWNER_INFO_SUCCESS = 'OWNER_INFO_SUCCESS'
export const OWNER_INFO_FAILURE = 'OWNER_INFO_FAILURE'
