// data comes from https://raw.githubusercontent.com/enaqx/awesome-react/master/README.md

// const links = data
//   .split('(')
//   .filter(d => d.slice(0,18) === 'https://github.com')
//   .join(')')
//   .split(')')
//   .filter(d => d.slice(0,18) === 'https://github.com')
//   .join('')
//   .split('https://github.com/')
//   .map(d => {
//     const text = d.split('/')
//     return {login: text[0], name: text[1]}
//   })
//   .filter(link => link.name)
//   .sort((a, b) => {
//     if(a.login < b.login) return -1
//     if(a.login > b.login) return 1
//     return 0
//   })
//   .filter(item => item.name.includes('.'))

const list = [
  {
    login: '1ven',
    name: 'do'
  }, {
    login: '7kfpun',
    name: 'FinanceReactNative'
  }, {
    login: 'Aetet',
    name: 'react-calendar'
  }, {
    login: 'AndrewHathaway',
    name: 'ReactSortableDataMixin'
  }, {
    login: 'AppliedMathematicsANU',
    name: 'plexus-form'
  }, {
    login: 'BinaryMuse',
    name: 'fluxxor'
  }, {
    login: 'BinaryMuse',
    name: 'imgsible'
  }, {
    login: 'BinaryMuse',
    name: 'wow-realm-status-react'
  }, {
    login: 'Chrisui',
    name: 'react-hotkeys'
  }, {
    login: 'Day8',
    name: 're-frame'
  }, {
    login: 'DveMac',
    name: 'semantic-react'
  }, {
    login: 'Flipboard',
    name: 'react-canvas'
  }, {
    login: 'ForbesLindesay',
    name: 'react-jade'
  }, {
    login: 'FormidableLabs',
    name: 'victory'
  }, {
    login: 'FormidableLabs',
    name: 'radium'
  }, {
    login: 'FredericHeem',
    name: 'starhackit'
  }, {
    login: 'Hacker0x01',
    name: 'react-datepicker'
  }, {
    login: 'HubSpot',
    name: 'react-experiments'
  }, {
    login: 'Jackong',
    name: 'generator-reactapp'
  }, {
    login: 'JedWatson',
    name: 'react-select'
  }, {
    login: 'KnisterPeter',
    name: 'jreact'
  }, {
    login: 'Kureev',
    name: 'react-native-side-menu'
  }, {
    login: 'KyleAMathews',
    name: 'react-sparkline'
  }, {
    login: 'KyleAMathews',
    name: 'react-micro-bar-chart'
  }, {
    login: 'KyleAMathews',
    name: 'react-component-width-mixin'
  }, {
    login: 'KyleAMathews',
    name: 'react-spinkit'
  }, {
    login: 'KyleAMathews',
    name: 'react-markdown-textarea'
  }, {
    login: 'KyleAMathews',
    name: 'react-smart-time-ago'
  }, {
    login: 'KyleAMathews',
    name: 'react-autoupdate-time'
  }, {
    login: 'KyleAMathews',
    name: 'react-gravatar'
  }, {
    login: 'LouisBarranqueiro',
    name: 'reapop'
  }, {
    login: 'MIJOTHY',
    name: 'FOR_FLUX_SAKE'
  }, {
    login: 'MandarinConLaBarba',
    name: 'react-tree-menu'
  }, {
    login: 'MandarinConLaBarba',
    name: 'flux-immutable-todomvc'
  }, {
    login: 'MattMcFarland',
    name: 'react-markdown-area'
  }, {
    login: 'MicheleBertoli',
    name: 'css-in-js'
  }, {
    login: 'MicheleBertoli',
    name: 'react-gmaps'
  }, {
    login: 'Microsoft',
    name: 'TypeScript'
  }, {
    login: 'Microsoft',
    name: 'react-native-code-push'
  }, {
    login: 'OlegIlyenko',
    name: 'sangria'
  }, {
    login: 'PixelsCommander',
    name: 'ReactiveElements'
  }, {
    login: 'RickWong',
    name: 'react-transmit'
  }, {
    login: 'RisingStack',
    name: 'graffiti'
  }, {
    login: 'STRML',
    name: 'react-localstorage'
  }, {
    login: 'SUI-Components',
    name: 'generator-sui-react'
  }, {
    login: 'SanderSpies',
    name: 'react-material'
  }, {
    login: 'Theadd',
    name: 'react-panels'
  }, {
    login: 'VinSpee',
    name: 'react-gcal-events-list'
  }, {
    login: 'Volicon',
    name: 'valuelink'
  }, {
    login: 'Volicon',
    name: 'NestedTypes'
  }, {
    login: 'Volicon',
    name: 'NestedReact'
  }, {
    login: 'Wildhoney',
    name: 'Keo'
  }, {
    login: 'Yomguithereal',
    name: 'react-blessed'
  }, {
    login: 'Yomguithereal',
    name: 'baobab'
  }, {
    login: 'Yomguithereal',
    name: 'baobab-react'
  }, {
    login: 'acdlite',
    name: 'flummox'
  }, {
    login: 'adazzle',
    name: 'react-data-grid'
  }, {
    login: 'adelevie',
    name: 'react-tags'
  }, {
    login: 'afonsopacifer',
    name: 'react-pomodoro'
  }, {
    login: 'airbnb',
    name: 'enzyme'
  }, {
    login: 'alex3165',
    name: 'react-mapbox-gl'
  }, {
    login: 'andimarek',
    name: 'graphql-java'
  }, {
    login: 'andrejewski',
    name: 'reactbone'
  }, {
    login: 'andrewgleave',
    name: 'react-weather'
  }, {
    login: 'andrewhathaway',
    name: 'Winterfell'
  }, {
    login: 'andrewngu',
    name: 'sound-redux'
  }, {
    login: 'andreypopp',
    name: 'react-textarea-autosize'
  }, {
    login: 'andreypopp',
    name: 'react-pad'
  }, {
    login: 'andreypopp',
    name: 'react-time'
  }, {
    login: 'andreypopp',
    name: 'react-async'
  }, {
    login: 'andreypopp',
    name: 'reactdown'
  }, {
    login: 'ant-design',
    name: 'ant-design'
  }, {
    login: 'appleboy',
    name: 'react-recaptcha'
  }, {
    login: 'apptailor',
    name: 'react-native-google-signin'
  }, {
    login: 'arkency',
    name: 'reactjs_koans'
  }, {
    login: 'arnaudbenard',
    name: 'redux-mock-store'
  }, {
    login: 'arnemart',
    name: 'react-topcoat'
  }, {
    login: 'arqex',
    name: 'freezer'
  }, {
    login: 'asbjornenge',
    name: 'react-datalist'
  }, {
    login: 'azmenak',
    name: 'react-stripe-checkout'
  }, {
    login: 'babel',
    name: 'babel-sublime'
  }, {
    login: 'babel',
    name: 'babel-sublime-snippets'
  }, {
    login: 'banyan',
    name: 'react-autolink'
  }, {
    login: 'banyan',
    name: 'react-emoji'
  }, {
    login: 'bartonhammond',
    name: 'snowflake'
  }, {
    login: 'benoitvallon',
    name: 'react-native-nw-react-calculator'
  }, {
    login: 'bgerm',
    name: 'react-table-sorter-demo'
  }, {
    login: 'bokuweb',
    name: 'react-resizable-box'
  }, {
    login: 'bokuweb',
    name: 'react-motion-menu'
  }, {
    login: 'bokuweb',
    name: 'react-sortable-pane'
  }, {
    login: 'bokuweb',
    name: 'react-resizable-and-movable'
  }, {
    login: 'brainfock',
    name: 'brainfock'
  }, {
    login: 'brysgo',
    name: 'graphql-bookshelf'
  }, {
    login: 'callemall',
    name: 'material-ui'
  }, {
    login: 'cameronjroe',
    name: 'react-star-rating'
  }, {
    login: 'captivationsoftware',
    name: 'react-sticky'
  }, {
    login: 'carlosrocha',
    name: 'react-data-components'
  }, {
    login: 'casesandberg',
    name: 'reactcss'
  }, {
    login: 'cauealves',
    name: 'react-pagespeed-score'
  }, {
    login: 'chadpaulson',
    name: 'react-cassette-player'
  }, {
    login: 'chenglou',
    name: 'react-chosen'
  }, {
    login: 'chenglou',
    name: 'RCSS'
  }, {
    login: 'chenglou',
    name: 'react-motion'
  }, {
    login: 'chenglou',
    name: 'react-tween-state'
  }, {
    login: 'chenglou',
    name: 'react-treeview'
  }, {
    login: 'chenglou',
    name: 'react-spinner'
  }, {
    login: 'chenglou',
    name: 'react-lights-out'
  }, {
    login: 'chentsulin',
    name: 'sweetalert-react'
  }, {
    login: 'choonkending',
    name: 'react-webpack-node'
  }, {
    login: 'christianalfoni',
    name: 'react-webpack-cookbook'
  }, {
    login: 'christianalfoni',
    name: 'formsy-react'
  }, {
    login: 'cht8687',
    name: 'react-expandable-listview'
  }, {
    login: 'cht8687',
    name: 'react-listview-sticky-header'
  }, {
    login: 'clariussystems',
    name: 'react-ios-switch'
  }, {
    login: 'codefoundries',
    name: 'UniversalRelayBoilerplate'
  }, {
    login: 'coinbolt',
    name: 'catshop'
  }, {
    login: 'coryhouse',
    name: 'react-slingshot'
  }, {
    login: 'corymsmith',
    name: 'react-native-icons'
  }, {
    login: 'danielstocks',
    name: 'react-sortable'
  }, {
    login: 'davidchang',
    name: 'ngReact'
  }, {
    login: 'ddispaltro',
    name: 'sbt-reactjs'
  }, {
    login: 'dittos',
    name: 'graphqllib'
  }, {
    login: 'dok',
    name: 'expose'
  }, {
    login: 'duereg',
    name: 'express-coffee-react-views'
  }, {
    login: 'duncanbeevers',
    name: 'jade-react'
  }, {
    login: 'duncanbeevers',
    name: 'gulp-jade-react'
  }, {
    login: 'dustingetz',
    name: 'react-json-editor'
  }, {
    login: 'dustingetz',
    name: 'react-cursor'
  }, {
    login: 'eiriklv',
    name: 'react-masonry-mixin'
  }, {
    login: 'eiriklv',
    name: 'react-packery-mixin'
  }, {
    login: 'elierotenberg',
    name: 'react-rails'
  }, {
    login: 'elierotenberg',
    name: 'react-animate'
  }, {
    login: 'eliseumds',
    name: 'react-autocomplete'
  }, {
    login: 'elucidata',
    name: 'react-coffee'
  }, {
    login: 'enaqx',
    name: 'react-kaomoji'
  }, {
    login: 'enaqx',
    name: 'js-object-to-table'
  }, {
    login: 'enigma-io',
    name: 'react-input-placeholder'
  }, {
    login: 'entrendipity',
    name: 'imvvm'
  }, {
    login: 'ericclemmons',
    name: 'react-resolver'
  }, {
    login: 'erikras',
    name: 'redux-form'
  }, {
    login: 'erikras',
    name: 'react-redux-universal-hot-example'
  }, {
    login: 'esbullington',
    name: 'react-d3'
  }, {
    login: 'facebook',
    name: 'flux'
  }, {
    login: 'facebook',
    name: 'relay'
  }, {
    login: 'facebook',
    name: 'graphql'
  }, {
    login: 'facebook',
    name: 'react-devtools'
  }, {
    login: 'facebook',
    name: 'react-art'
  }, {
    login: 'facebook',
    name: 'react-native'
  }, {
    login: 'facebook',
    name: 'react-native-fbsdk'
  }, {
    login: 'facebook',
    name: 'immutable-js'
  }, {
    login: 'facebook',
    name: 'jscodeshift'
  }, {
    login: 'facebook',
    name: 'flow'
  }, {
    login: 'facebook',
    name: 'react'
  }, {
    login: 'facebookincubator',
    name: 'create-react-app'
  }, {
    login: 'fatiherikli',
    name: 'fil'
  }, {
    login: 'fdecampredon',
    name: 'react-rxjs-todomvc'
  }, {
    login: 'fdecampredon',
    name: 'rx-react'
  }, {
    login: 'fdecampredon',
    name: 'react-observe-todomvc'
  }, {
    login: 'fdecampredon',
    name: 'react-typescript'
  }, {
    login: 'firebase',
    name: 'reactfire'
  }, {
    login: 'fpco',
    name: 'stackage-view'
  }, {
    login: 'freiksenet',
    name: 'react-kinetic'
  }, {
    login: 'fujimura',
    name: 'purescript-react-example'
  }, {
    login: 'gabrielbull',
    name: 'react-desktop'
  }, {
    login: 'gabrielbull',
    name: 'react-aim'
  }, {
    login: 'gaearon',
    name: 'redux-thunk'
  }, {
    login: 'gaearon',
    name: 'redux'
  }, {
    login: 'gaearon',
    name: 'react-transform-hmr'
  }, {
    login: 'gaearon',
    name: 'react-document-title'
  }, {
    login: 'gaearon',
    name: 'react-dnd'
  }, {
    login: 'gaearon',
    name: 'redux-devtools'
  }, {
    login: 'gajus',
    name: 'redux-immutable'
  }, {
    login: 'gaperton',
    name: 'todomvc-nestedreact'
  }, {
    login: 'gatsbyjs',
    name: 'gatsby'
  }, {
    login: 'gcanti',
    name: 'tcomb-react'
  }, {
    login: 'glennreyes',
    name: 'react-countup'
  }, {
    login: 'glittershark',
    name: 'reactable'
  }, {
    login: 'glortho',
    name: 'react-keydown'
  }, {
    login: 'goatslacker',
    name: 'alt'
  }, {
    login: 'gorangajic',
    name: 'react-svg-morph'
  }, {
    login: 'gorangajic',
    name: 'react-icons'
  }, {
    login: 'gpbl',
    name: 'isomorphic500'
  }, {
    login: 'gragland',
    name: 'instatype'
  }, {
    login: 'graphql',
    name: 'express-graphql'
  }, {
    login: 'graphql',
    name: 'graphql-relay-js'
  }, {
    login: 'graphql',
    name: 'graphql-js'
  }, {
    login: 'graphql-dotnet',
    name: 'graphql-dotnet'
  }, {
    login: 'graphql-go',
    name: 'graphql'
  }, {
    login: 'gritzko',
    name: 'swarm'
  }, {
    login: 'gritzko',
    name: 'todomvc-swarm'
  }, {
    login: 'grncdr',
    name: 'react-async-input'
  }, {
    login: 'grommet',
    name: 'grommet'
  }, {
    login: 'guillaumervls',
    name: 'react-ellipsis'
  }, {
    login: 'guillaumervls',
    name: 'react-infinite-scroll'
  }, {
    login: 'haochuan',
    name: 'random-notes'
  }, {
    login: 'happypoulp',
    name: 'redux-tutorial'
  }, {
    login: 'hurrymaplelad',
    name: 'teact'
  }, {
    login: 'hustcc',
    name: 'echarts-for-react'
  }, {
    login: 'hzdg',
    name: 'reactdi'
  }, {
    login: 'hzdg',
    name: 'react-loadermixin'
  }, {
    login: 'hzdg',
    name: 'react-imageloader'
  }, {
    login: 'hzdg',
    name: 'gsap-react-plugin'
  }, {
    login: 'hzdg',
    name: 'react-google-analytics'
  }, {
    login: 'hzdg',
    name: 'react-pressable'
  }, {
    login: 'hzdg',
    name: 'react-loadqueueloader'
  }, {
    login: 'iSimar',
    name: 'HackerNews-React-Native'
  }, {
    login: 'ikr',
    name: 'react-star-rating-input'
  }, {
    login: 'insin',
    name: 'newforms'
  }, {
    login: 'insin',
    name: 'msx'
  }, {
    login: 'insin',
    name: 'lifequote'
  }, {
    login: 'insin',
    name: 'reactodo'
  }, {
    login: 'insin',
    name: 'react-hn'
  }, {
    login: 'instructure',
    name: 'react-tokeninput'
  }, {
    login: 'instructure',
    name: 'react-select-box'
  }, {
    login: 'istarkov',
    name: 'google-map-react'
  }, {
    login: 'jamesmacaulay',
    name: 'react-bacon'
  }, {
    login: 'japgolly',
    name: 'scalajs-react'
  }, {
    login: 'jaredly',
    name: 'github-issues-viewer'
  }, {
    login: 'jasonslyvia',
    name: 'react-anything-sortable'
  }, {
    login: 'jbgutierrez',
    name: 'vim-babel'
  }, {
    login: 'jbkuczma',
    name: 'NBAreact'
  }, {
    login: 'jed',
    name: 'react-swipe'
  }, {
    login: 'jedireza',
    name: 'hapi-react-views'
  }, {
    login: 'jedireza',
    name: 'aqua'
  }, {
    login: 'jeroencoumans',
    name: 'react-scroll-components'
  }, {
    login: 'jeroencoumans',
    name: 'react-fullscreen-component'
  }, {
    login: 'jhudson8',
    name: 'react-events'
  }, {
    login: 'jhudson8',
    name: 'backbone-reaction'
  }, {
    login: 'jhudson8',
    name: 'react-mixin-manager'
  }, {
    login: 'jhudson8',
    name: 'react-chartjs'
  }, {
    login: 'jhudson8',
    name: 'react-semantic-ui'
  }, {
    login: 'jhudson8',
    name: 'react-backbone'
  }, {
    login: 'jl-',
    name: 'react-slide-deck'
  }, {
    login: 'joelburget',
    name: 'react-haskell'
  }, {
    login: 'jondot',
    name: 'awesome-react-native'
  }, {
    login: 'josephsavona',
    name: 'valuable'
  }, {
    login: 'jpuri',
    name: 'react-range-slider'
  }, {
    login: 'jrowny',
    name: 'react-absolute-grid'
  }, {
    login: 'jsdf',
    name: 'coffee-react'
  }, {
    login: 'jsdf',
    name: 'sprockets-coffee-react'
  }, {
    login: 'jsdf',
    name: 'coffee-react-transform'
  }, {
    login: 'jsdf',
    name: 'react-layout'
  }, {
    login: 'jsdir',
    name: 'react-ladda'
  }, {
    login: 'justinj',
    name: 'vim-react-snippets'
  }, {
    login: 'jxnblk',
    name: 'rebass'
  }, {
    login: 'kadirahq',
    name: 'react-storybook'
  }, {
    login: 'kennetpostigo',
    name: 'react-facebook-login-component'
  }, {
    login: 'kennetpostigo',
    name: 'react-google-login-component'
  }, {
    login: 'kenwheeler',
    name: 'mcfly'
  }, {
    login: 'keystonejs',
    name: 'keystone'
  }, {
    login: 'khan',
    name: 'perseus'
  }, {
    login: 'kjda',
    name: 'react-topui'
  }, {
    login: 'kriasoft',
    name: 'aspnet-starter-kit'
  }, {
    login: 'kriasoft',
    name: 'fsharp-starter-kit'
  }, {
    login: 'kriasoft',
    name: 'react-starter-kit'
  }, {
    login: 'kriasoft',
    name: 'react-app'
  }, {
    login: 'laem',
    name: 'react-horizontal-bar-chart'
  }, {
    login: 'levand',
    name: 'quiescent'
  }, {
    login: 'luqin',
    name: 'react-icheck'
  }, {
    login: 'magalhas',
    name: 'backbone-react-component'
  }, {
    login: 'mapbox',
    name: 'react-native-mapbox-gl'
  }, {
    login: 'markafoni',
    name: 'react-livestamp'
  }, {
    login: 'markdalgleish',
    name: 'redux-analytics'
  }, {
    login: 'markdalgleish',
    name: 'static-site-generator-webpack-plugin'
  }, {
    login: 'martinandert',
    name: 'react-interpolate-component'
  }, {
    login: 'martinandert',
    name: 'react-lorem-component'
  }, {
    login: 'martinandert',
    name: 'react-translate-component'
  }, {
    login: 'martinandert',
    name: 'react-ago-component'
  }, {
    login: 'martyjs',
    name: 'marty'
  }, {
    login: 'matnel',
    name: 'react-maps'
  }, {
    login: 'matthewwithanm',
    name: 'react-inlinesvg'
  }, {
    login: 'matthewwithanm',
    name: 'react-controllables'
  }, {
    login: 'matthewwithanm',
    name: 'react-frozenhead'
  }, {
    login: 'matthewwithanm',
    name: 'react-mediaswitch'
  }, {
    login: 'mbasso',
    name: 'react-https-redirect'
  }, {
    login: 'mbasso',
    name: 'react-http-request'
  }, {
    login: 'mbasso',
    name: 'react-browser-detection'
  }, {
    login: 'meiersi',
    name: 'blaze-react'
  }, {
    login: 'mhart',
    name: 'react-server-example'
  }, {
    login: 'mickhansen',
    name: 'graphql-sequelize'
  }, {
    login: 'mikechau',
    name: 'react-primer-draft'
  }, {
    login: 'misino',
    name: 'react-datepicker'
  }, {
    login: 'mjohnston',
    name: 'react-native-webpack-server'
  }, {
    login: 'mking',
    name: 'react-hn'
  }, {
    login: 'mobxjs',
    name: 'mobx'
  }, {
    login: 'mobxjs',
    name: 'mobx-react'
  }, {
    login: 'mohebifar',
    name: 'racket'
  }, {
    login: 'moreartyjs',
    name: 'moreartyjs'
  }, {
    login: 'moroshko',
    name: 'react-autosuggest'
  }, {
    login: 'mozilla',
    name: 'payments-ui'
  }, {
    login: 'mquan',
    name: 'cortex'
  }, {
    login: 'muut',
    name: 'riotjs'
  }, {
    login: 'mxw',
    name: 'vim-jsx'
  }, {
    login: 'mzabriskie',
    name: 'react-draggable'
  }, {
    login: 'mzabriskie',
    name: 'react-tabs'
  }, {
    login: 'nambrot',
    name: 'rails-webpack-react-flux'
  }, {
    login: 'nashvail',
    name: 'SplashWalls'
  }, {
    login: 'natew',
    name: 'reactor-demo'
  }, {
    login: 'newtriks',
    name: 'generator-react-webpack'
  }, {
    login: 'ngokevin',
    name: 'react-file-reader-input'
  }, {
    login: 'ngokevin',
    name: 'aframe'
  }, {
    login: 'nmn',
    name: 'react-timeago'
  }, {
    login: 'nmn',
    name: 'react-infinity'
  }, {
    login: 'oblador',
    name: 'react-native-vector-icons'
  }, {
    login: 'olahol',
    name: 'react-tagsinput'
  }, {
    login: 'olebedev',
    name: 'go-starter-kit'
  }, {
    login: 'omnidan',
    name: 'redux-undo'
  }, {
    login: 'omniscientjs',
    name: 'omniscient'
  }, {
    login: 'omniscientjs',
    name: 'immstruct'
  }, {
    login: 'optimizely',
    name: 'nuclear-js'
  }, {
    login: 'orgsync',
    name: 'olay-react'
  }, {
    login: 'orgsync',
    name: 'react-list'
  }, {
    login: 'paramaggarwal',
    name: 'react-dropzone'
  }, {
    login: 'passy',
    name: 'react-pokemon'
  }, {
    login: 'paularmstrong',
    name: 'normalizr'
  }, {
    login: 'pauldotknopf',
    name: 'react-aspnet-boilerplate'
  }, {
    login: 'paypal',
    name: 'react-engine'
  }, {
    login: 'pedronauck',
    name: 'react-video'
  }, {
    login: 'pedronauck',
    name: 'react-simpletabs'
  }, {
    login: 'petehunt',
    name: 'react-touch'
  }, {
    login: 'petehunt',
    name: 'wolfenstein3D-react'
  }, {
    login: 'petehunt',
    name: 'jsxstyle'
  }, {
    login: 'petehunt',
    name: 'webpack-howto'
  }, {
    login: 'petehunt',
    name: 'react-server-rendering-example'
  }, {
    login: 'pieterv',
    name: 'react-googlemaps'
  }, {
    login: 'pieterv',
    name: 'react-layers'
  }, {
    login: 'pilwon',
    name: 'react-famous'
  }, {
    login: 'planningcenter',
    name: 'react-patterns'
  }, {
    login: 'plaxdan',
    name: 'react-topcoat'
  }, {
    login: 'pocotan001',
    name: 'react-styleguide-generator'
  }, {
    login: 'pqx',
    name: 'react-frame'
  }, {
    login: 'pqx',
    name: 'react-ui-tree'
  }, {
    login: 'prometheusresearch',
    name: 'react-grid'
  }, {
    login: 'prometheusresearch',
    name: 'react-forms'
  }, {
    login: 'prometheusresearch',
    name: 'react-autocomplete'
  }, {
    login: 'purescript-contrib',
    name: 'purescript-react'
  }, {
    login: 'quri',
    name: 'react-bootstrap-datetimepicker'
  }, {
    login: 'quri',
    name: 'react-form-builder'
  }, {
    login: 'rackt',
    name: 'react-autocomplete'
  }, {
    login: 'randylien',
    name: 'generator-react-gulp-browserify'
  }, {
    login: 'react-bootstrap',
    name: 'react-bootstrap'
  }, {
    login: 'reactjs',
    name: 'redux'
  }, {
    login: 'reactjs',
    name: 'react-router'
  }, {
    login: 'reactjs',
    name: 'express-react-views'
  }, {
    login: 'reactjs',
    name: 'react-page-middleware'
  }, {
    login: 'reactjs',
    name: 'react-rails'
  }, {
    login: 'reactjs',
    name: 'react-python'
  }, {
    login: 'reactjs',
    name: 'react-php-v8js'
  }, {
    login: 'reactjs',
    name: 'reselect'
  }, {
    login: 'reactjs',
    name: 'react-router-redux'
  }, {
    login: 'reactjs',
    name: 'react-docgen'
  }, {
    login: 'reactjs',
    name: 'react-redux'
  }, {
    login: 'reactjs',
    name: 'react-magic'
  }, {
    login: 'reactjs',
    name: 'core-notes'
  }, {
    login: 'reactjs',
    name: 'react-meteor'
  }, {
    login: 'reagent-project',
    name: 'reagent'
  }, {
    login: 'redbadger',
    name: 'react-pillbox'
  }, {
    login: 'reddit',
    name: 'reddit-mobile'
  }, {
    login: 'redux-observable',
    name: 'redux-observable'
  }, {
    login: 'relay-tools',
    name: 'react-router-relay'
  }, {
    login: 'relay-tools',
    name: 'relay-local-schema'
  }, {
    login: 'rexxars',
    name: 'react-element-pan'
  }, {
    login: 'rmosolgo',
    name: 'graphql-ruby'
  }, {
    login: 'rrag',
    name: 'react-stockcharts'
  }, {
    login: 'rtfeldman',
    name: 'seamless-immutable'
  }, {
    login: 'ruahman',
    name: 'rpm-xtags-rivets-finch-react'
  }, {
    login: 'ryanseddon',
    name: 'react-frame-component'
  }, {
    login: 'searchkit',
    name: 'searchkit'
  }, {
    login: 'securingsincity',
    name: 'backbone-react-ui'
  }, {
    login: 'simonsmith',
    name: 'webpack-example'
  }, {
    login: 'sindresorhus',
    name: 'awesome'
  }, {
    login: 'skellock',
    name: 'reactotron'
  }, {
    login: 'skratchdot',
    name: 'react-bootstrap-daterangepicker'
  }, {
    login: 'skratchdot',
    name: 'react-bootstrap-multiselect'
  }, {
    login: 'smanne',
    name: 'reduxnor'
  }, {
    login: 'snd',
    name: 'react-kup'
  }, {
    login: 'solidsnack',
    name: 'GraphpostgresQL'
  }, {
    login: 'sonnylazuardi',
    name: 'ziliun-react-native'
  }, {
    login: 'souhe',
    name: 'reactScrollbar'
  }, {
    login: 'spoike',
    name: 'refluxjs'
  }, {
    login: 'ssorallen',
    name: 'react-play'
  }, {
    login: 'ssorallen',
    name: 'react-todos'
  }, {
    login: 'ssorallen',
    name: 'turbo-react'
  }, {
    login: 'stayradiated',
    name: 'react-colorpicker'
  }, {
    login: 'steida',
    name: 'este'
  }, {
    login: 'swannodette',
    name: 'om'
  }, {
    login: 'swannodette',
    name: 'mori'
  }, {
    login: 'swipely',
    name: 'state-trooper'
  }, {
    login: 'syranide',
    name: 'react-swf'
  }, {
    login: 'syranide',
    name: 'react-unmount-listener-mixin'
  }, {
    login: 'tajo',
    name: 'react-portal'
  }, {
    login: 'takeoutweight',
    name: 'shade-todomvc'
  }, {
    login: 'talyssonoc',
    name: 'react-laravel'
  }, {
    login: 'text-mask',
    name: 'text-mask'
  }, {
    login: 'theaqua',
    name: 'redux-logger'
  }, {
    login: 'theporchrat',
    name: 'react-widgets'
  }, {
    login: 'tj',
    name: 'frontend-boilerplate'
  }, {
    login: 'tleunen',
    name: 'react-clickdrag-mixin'
  }, {
    login: 'tleunen',
    name: 'react-number-editor'
  }, {
    login: 'tomchentw',
    name: 'react-google-maps'
  }, {
    login: 'tonsky',
    name: 'datascript'
  }, {
    login: 'tonyspiro',
    name: 'react-flux-cosmicjs'
  }, {
    login: 'tonyspiro',
    name: 'react-typeahead-search'
  }, {
    login: 'treasure-data',
    name: 'redux-search'
  }, {
    login: 'uber',
    name: 'react-map-gl'
  }, {
    login: 'unimonkiez',
    name: 'react-cordova-boilerplate'
  }, {
    login: 'ustun',
    name: 'react-mvc'
  }, {
    login: 'uxcore',
    name: 'uxcore'
  }, {
    login: 'vaffel',
    name: 'sql-to-graphql'
  }, {
    login: 'vjeux',
    name: 'markdown-react'
  }, {
    login: 'vjeux',
    name: 'react-xtags'
  }, {
    login: 'vojtajina',
    name: 'react-with-di'
  }, {
    login: 'voronianski',
    name: 'flux-comparison'
  }, {
    login: 'vutran',
    name: 'react-offcanvas'
  }, {
    login: 'wangzuo',
    name: 'react-input-slider'
  }, {
    login: 'wangzuo',
    name: 'react-progress-label'
  }, {
    login: 'wangzuo',
    name: 'react-medium-editor'
  }, {
    login: 'wangzuo',
    name: 'react-input-color'
  }, {
    login: 'wearefractal',
    name: 'react-responsive'
  }, {
    login: 'webbylab',
    name: 'itsquiz-wall'
  }, {
    login: 'webonyx',
    name: 'graphql-php'
  }, {
    login: 'webpack',
    name: 'react-proxy-loader'
  }, {
    login: 'wereHamster',
    name: 'avers'
  }, {
    login: 'wingspan',
    name: 'wingspan-forms'
  }, {
    login: 'wix',
    name: 'react-templates'
  }, {
    login: 'wyvernnot',
    name: 'react-datatables-example'
  }, {
    login: 'xeodou',
    name: 'react-crouton'
  }, {
    login: 'xgrommx',
    name: 'awesome-redux'
  }, {
    login: 'yahoo',
    name: 'react-intl'
  }, {
    login: 'yahoo',
    name: 'react-i13n'
  }, {
    login: 'yahoo',
    name: 'fluxible'
  }, {
    login: 'yahoo',
    name: 'flux-examples'
  }, {
    login: 'yannickcr',
    name: 'eslint-plugin-react'
  }, {
    login: 'yelouafi',
    name: 'redux-saga'
  }, {
    login: 'yongxu',
    name: 'react-DnR'
  }, {
    login: 'yoshuawuyts',
    name: 'react-anchor'
  }, {
    login: 'zackify',
    name: 'formjs'
  }, {
    login: 'zippyui',
    name: 'react-datagrid'
  }
]


export const genRandomReactLink = () => list[Math.floor(Math.random() * list.length)]
